# Generated by Django 4.1.5 on 2023-01-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_variacao_preco_promocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing_promocional',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Preço Promocional'),
        ),
    ]
