# Generated by Django 4.1.5 on 2023-01-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_alter_produto_preco_marketing_promocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing_promocional',
            field=models.FloatField(default=0, verbose_name='Preço Promocional'),
        ),
    ]
